# Generated by Django 5.1.3 on 2024-12-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('hoursOfSupport', models.IntegerField()),
                ('workers', models.IntegerField()),
            ],
        ),
    ]
