# Generated by Django 5.1.3 on 2024-12-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='client',
            new_name='foundChildren',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='hoursOfSupport',
            new_name='missingChildren',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='projects',
            new_name='reportedChildren',
        ),
    ]
