# Generated by Django 5.1.3 on 2024-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='customisableImage',
            field=models.ImageField(default='images/happy-family.avif', upload_to='media'),
        ),
    ]
