# Generated by Django 5.1.3 on 2024-12-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_analytic_customisableimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='year',
            field=models.IntegerField(default='2024'),
        ),
    ]
