# Generated by Django 5.1.3 on 2024-12-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_analytic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('middleName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=3)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('skinTone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=256)),
                ('dressing', models.TextField()),
                ('profilePhoto', models.ImageField(upload_to='media/Reported-Children')),
            ],
        ),
    ]
