# Generated by Django 4.2.16 on 2024-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='profilePhoto',
            field=models.ImageField(upload_to='media/ReportedChildren'),
        ),
    ]
